# Generated by Django 6.0 on 2026-01-01 04:29

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "text",
                    models.TextField(help_text="Original company information text"),
                ),
                (
                    "vector",
                    pgvector.django.vector.VectorField(
                        dimensions=768, help_text="Vector embedding (768 dimensions)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional info like language, category",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "company_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="company_doc_created_4edd57_idx"
                    )
                ],
            },
        ),
    ]
